# fly.toml app configuration file generated for old-wind-8748 on 2023-04-30T18:59:06+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "old-wind-8748"
primary_region = "arn"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080 
  processes = ["app"]